name: Array_App
description: Array A Digital Wardrobe Application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0" #<3.0.0"
  flutter: 3.3.10

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  very_good_analysis: ^4.0.0+1 # should move to dev
  lints: ^2.0.1  # //TODO check for removal
  flutter_lints: ^2.0.1 # //TODO check for removal
  shared_preferences: ^2.0.6
  fluttertoast: ^8.1.2
  dio: ^5.0.1
  json_serializable: ^6.6.1
  stream_transform: ^2.1.0
  logger: ^1.0.0
  equatable: ^2.0.5
  json_annotation: ^4.8.0
  flutter_dotenv: ^5.0.2
  index_generator: ^3.3.3
  http: ^0.13.5
  camera_platform_interface: ^2.4.1
  camera: ^0.10.3+2
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.13
  url_launcher: ^6.1.10
  open_file: ^3.2.1
  remove_background: ^0.0.1
  image_picker: ^0.8.6+4
  gallery_saver: ^2.3.2
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  widgets_to_image: ^0.0.2
  dynamic_color: ^1.6.3

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  mockito: ^5.0.15

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/add_item_details/
    - .env

targets:
  $default:
    builders:
      json_serializable:
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          #
          # The default value for each is listed.
          any_map: false
          checked: false
          constructor: ""
          create_factory: true
          create_field_map: false
          create_per_field_to_json: false
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true