name: Array_App
description: Array A Digital Wardrobe Application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0" #<3.0.0"
  flutter: 3.3.10

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  very_good_analysis: ^3.1.0 # should move to dev
  lints: ^2.0.1  # //TODO check for removal
  flutter_lints: ^2.0.1 # //TODO check for removal
  shared_preferences: ^2.0.6
  fluttertoast: ^8.1.2
  dio: ^5.0.1
  json_serializable: ^6.6.1
  stream_transform: ^2.1.0
  logger: ^1.0.0
  equatable: ^2.0.5
  json_annotation: ^4.8.0
  flutter_dotenv: ^5.0.2
  index_generator: ^3.3.3
  http: ^0.13.5
  camera_platform_interface: ^2.4.1
  camera: ^0.10.3+2
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.13
  url_launcher: ^6.1.10
  open_file: ^3.2.1
  remove_background: ^0.0.1
  image_picker: ^0.8.6+4
  gallery_saver: ^2.3.2

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - .env
