import 'package:flutter/material.dart';

class CScheme {
  static const light = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF892CC6),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFF3DAFF),
    onPrimaryContainer: Color(0xFF2F004C),
    secondary: Color(0xFFAC009F),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFFFD7F2),
    onSecondaryContainer: Color(0xFF390034),
    tertiary: Color(0xFF9C404A),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFFFDADB),
    onTertiaryContainer: Color(0xFF40000D),
    error: Color(0xFFBA1A1A),
    errorContainer: Color(0xFFFFDAD6),
    onError: Color(0xFFFFFFFF),
    onErrorContainer: Color(0xFF410002),
    background: Color(0xFFFFFBFF),
    onBackground: Color(0xFF1D1B1E),
    surface: Color(0xFFFFFBFF),
    onSurface: Color(0xFF1D1B1E),
    surfaceVariant: Color(0xFFEADFEA),
    onSurfaceVariant: Color(0xFF4B454D),
    outline: Color(0xFF7C747E),
    onInverseSurface: Color(0xFFF6EFF3),
    inverseSurface: Color(0xFF332F33),
    inversePrimary: Color(0xFFE3B5FF),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFF892CC6),
    outlineVariant: Color(0xFFCDC3CE),
    scrim: Color(0xFF000000),
  );

  static const dark = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFFE3B5FF),
    onPrimary: Color(0xFF4D007A),
    primaryContainer: Color(0xFF6E00AA),
    onPrimaryContainer: Color(0xFFF3DAFF),
    secondary: Color(0xFFFFACEC),
    onSecondary: Color(0xFF5D0056),
    secondaryContainer: Color(0xFF83007A),
    onSecondaryContainer: Color(0xFFFFD7F2),
    tertiary: Color(0xFFF4B7BA),
    onTertiary: Color(0xFF4C2528),
    tertiaryContainer: Color(0xFF663B3D),
    onTertiaryContainer: Color(0xFFFFDADA),
    error: Color(0xFFFFB4AB),
    errorContainer: Color(0xFF93000A),
    onError: Color(0xFF690005),
    onErrorContainer: Color(0xFFFFDAD6),
    background: Color(0xFF001F25),
    onBackground: Color(0xFFA6EEFF),
    surface: Color(0xFF001F25),
    onSurface: Color(0xFFA6EEFF),
    surfaceVariant: Color(0xFF4B454D),
    onSurfaceVariant: Color(0xFFCDC3CE),
    outline: Color(0xFF968E98),
    onInverseSurface: Color(0xFF001F25),
    inverseSurface: Color(0xFFA6EEFF),
    inversePrimary: Color(0xFF892CC6),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFFE3B5FF),
    outlineVariant: Color(0xFF4B454D),
    scrim: Color(0xFF000000),
  );
}
